services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    container_name: api
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./api:/chessmate
    restart: on-failure
